Replace (ImGuiTableFlags)NULL with ImGuiTableFlags_None
This is more portable; the cast can cause errors on some toolchains.
When compiling with musl, for example:

    error: cast from 'std::nullptr_t' to 'ImGuiTableFlags' {aka 'int'} loses precision